# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(798, 593)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 40, 151, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(410, 40, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 120, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(170, 120, 81, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 120, 81, 21))
        self.label.setObjectName("label")
        self.label_joint_angles = QtWidgets.QLabel(self.centralwidget)
        self.label_joint_angles.setGeometry(QtCore.QRect(380, 120, 241, 21))
        self.label_joint_angles.setObjectName("label_joint_angles")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(70, 10, 421, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 40, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 150, 101, 21))
        self.label_2.setObjectName("label_2")
        self.label_end_effector_pos_label = QtWidgets.QLabel(self.centralwidget)
        self.label_end_effector_pos_label.setGeometry(QtCore.QRect(380, 150, 241, 21))
        self.label_end_effector_pos_label.setObjectName("label_end_effector_pos_label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 170, 101, 21))
        self.label_3.setObjectName("label_3")
        self.label_end_effector_ori_label = QtWidgets.QLabel(self.centralwidget)
        self.label_end_effector_ori_label.setGeometry(QtCore.QRect(380, 170, 241, 21))
        self.label_end_effector_ori_label.setObjectName("label_end_effector_ori_label")
        self.update_robot_states_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.update_robot_states_check_box.setGeometry(QtCore.QRect(320, 100, 161, 16))
        self.update_robot_states_check_box.setObjectName("update_robot_states_check_box")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 798, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "run simulation"))
        self.pushButton_2.setText(_translate("MainWindow", "shut down"))
        self.pushButton_3.setText(_translate("MainWindow", "go to point"))
        self.lineEdit.setText(_translate("MainWindow", "[x,y,z]"))
        self.label.setText(_translate("MainWindow", "joint angles"))
        self.label_joint_angles.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_4.setText(_translate("MainWindow", "create pybullet env"))
        self.pushButton_5.setText(_translate("MainWindow", "load robot"))
        self.label_2.setText(_translate("MainWindow", "end effector pos"))
        self.label_end_effector_pos_label.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "end effector ori"))
        self.label_end_effector_ori_label.setText(_translate("MainWindow", "TextLabel"))
        self.update_robot_states_check_box.setText(_translate("MainWindow", "update robot states"))
